### ISSUE TITLE
Get_League_Listings not working when a league has a faulty URI

### ISSUE THREAD

**Issue by nickeeex** [Auo/dota2-api#1]
Example 
 {
"name": "#DOTA_Item_ProKits_Arena"
"leagueid": 3736
"description": "#DOTA_Item_Desc_ProKits_Arena"
"tournament_url": "Legionbattles.com, prokitsarena.com"
"itemdef": 16799
}

This tournament has two uri's, you could just ignore this and try to parse the returned uri with https://msdn.microsoft.com/en-us/library/ms131572(v=vs.110).aspx or change the type of the League tournamentUri property.

**Comment by Auo** [comment]
Thanks for bringing this up. I Implemented Uri.TryCreate for the StringUriConverter. Another possible fix was to create a list for Tournament_url. I've never before seen two URLs before in the field. 7866548d34fe9adfbd59b97ef5d8a2454864ada3
